root = "."

[build]
cmd = "go build -o ./cmd/api/tmp/api.exe ./cmd/api/main.go"
bin = "cmd/api/tmp/api.exe"
exclude_dir = ["tmp"]
exclude_file = ["build-errors.log"]
include_ext = ["go"]

[color]
build = "yellow"

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
